[package]
name = "render-hex"
version = "0.1.0"
authors = ["Tim McNamara <author@rustinaction.com>"]
edition = "2018"

[dependencies]
crossbeam = "0.8.4"
crossbeam-utils = "0.8.19"
rayon = "1.8.1"
svg = "0.14.0"
